apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan-10-production
  namespace: openshift-mtv
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-ex
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "vlan-10-production",
    "type": "bridge",
    "bridge": "br-ex",
    "vlan": 10,
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.10.0/24",
      "rangeStart": "192.168.10.100",
      "rangeEnd": "192.168.10.200",
      "gateway": "192.168.10.1",
      "routes": [
        {
          "dst": "0.0.0.0/0"
        }
      ]
    },
    "mtu": 1500,
    "isGateway": false,
    "hairpinMode": false,
    "promiscMode": false
  }'
